export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const CHANGE_SLIPPAGE = "CHANGE_SLIPPAGE";
export const CHANGE_SWITCH_SLIPPAGE = "CHANGE_SWITCH_SLIPPAGE";
export const CHANGE_SETTING_VISIBLE = "CHANGE_SETTING_VISIBLE";
