export const SET_SELECTOR_DIALOG_PARAMS = "SET_SELECTOR_DIALOG_PARAMS";
export const SET_WALLET_DIALOG_PARAMS_STATUS =
  "SET_WALLET_DIALOG_PARAMS_STATUS";
export const SET_CALLBACK_DIALOG_PARAMS_STATUS =
  "SET_CALLBACK_DIALOG_PARAMS_STATUS";
export const CHANGE_OPERATE_STATUS = "CHANGE_OPERATE_STATUS";
export const CHANGE_MAIN_STATUS = "CHANGE_MAIN_STATUS";
export const SET_SELECTED_ELEMENT_LIST = "SET_SELECTED_ELEMENT_LIST";
export const SET_META_DATA = "SET_META_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_CURR_NFT_PROPERTY = "SET_CURR_NFT_PROPERTY";
export const CLEAR_DATA = "CLEAR_DATA";
export const SET_CREATE_DIALOG_PARAMS = "SET_CREATE_DIALOG_PARAMS";
export const SET_ACTIVE_PROPERTY = "SET_ACTIVE_PROPERTY";
export const SET_MODULE_NAME = "SET_MODULE_NAME";
