export const TRANSFROM_CURRENCY = "TRANSFROM_CURRENCY";
export const CHANGE_INPUTVALUE = "CHANGE_INPUTVALUE";
export const SHOW_CALCALATOR_CARD = "SHOW_CALCALATOR_CAED";
export const SET_CURRENCY_INFO = "SET_CURRENCY_INFO";
export const SET_CALCALATOR_SWAP_DATA = "SET_CALCALATOR_SWAP_DATA";
export const CLEAR_SWAP_DATA = "CLEAR_SWAP_DATA";
export const CHANGE_CONFIRM_VISIBLE = "CHANGE_CONFIRM_VISIBLE";
export const SET_EXCHANGE_TOTAL_HISTORY = "SET_EXCHANGE_TOTAL_HISTORY";
