export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_STARMASK_ONBOARDING = "SET_STARMASK_ONBOARDING";
export const SET_STARMASK_PROVIDER = "SET_STARMASK_PROVIDER";
export const SET_CHIANID = "SET_STC_CHIANID";
export const SET_WALLET_BALANCE = "SET_WALLET_BALANCE";
export const SET_WALLET_CONNECT_STATUS = "SET_WALLET_CONNECT_STATUS";
export const SET_WALLET_NET_WORK_ID = "SET_WALLET_NET_WORK_ID";
export const CHANGE_WALLET_TIMER_STATUS = "CHANGE_WALLET_TIMER_STATUS";
