// 合成card素材id

const nftproto = {
  background_id: 0,
  fur_id: 0,
  clothes_id: 0,
  expression_id: 0,
  head_id: 0,
  accessories_id: 0,
  eyes_id: 0,
  hat_id: 0,
  costume_id: 0,
  makeup_id: 0,
  shoes_id: 0,
  mouth_id: 0,
  earring_id: 0,
  necklace_id: 0,
  neck_id: 0,
  hair_id: 0,
  horn_id: 0,
  hands_id: 0,
  body_id: 0,
  skin_id: 0,
  tattoo_id: 0,
  people_id: 0,
  characteristic_id: 0,
  hobby_id: 0,
  zodiac_id: 0,
  action_id: 0,
  toys_id: 0,
  fruits_id: 0,
  vegetables_id: 0,
  meat_id: 0,
  beverages_id: 0,
  food_id: 0,
  vehicle_id: 0,
  weather_id: 0,
  month_id: 0,
  sports_id: 0,
  music_id: 0,
  movies_id: 0,
  season_id: 0,
  outfit_id: 0,
  face_id: 0,
  arm_id: 0,
  leg_id: 0,
  foot_id: 0,
  weapon_id: 0,
  helmet_id: 0,
  armor_id: 0,
  mecha_id: 0,
  pants_id: 0,
  skirt_id: 0,
  left_hand_id: 0,
  right_hand_id: 0,
  pets_id: 0,
  gifts_id: 0,
  tail_id: 0,
};

const nftProtoArr = Object.values(nftproto);

export { nftproto, nftProtoArr };
